services:
  frontend:
    container_name: frontend
    build:
      context: ./docker/node
      target: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    tty: true
    ports:
      - "3000:3000"
      - "3001:3001"
  backend:
    container_name: backend
    build:
      context: ./docker/node
      target: backend
    working_dir: /app
    volumes:
      - ./backend:/app
    tty: true
    ports:
      - "8080:3000"
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: db
    image: postgres:15.1-alpine3.17
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - db-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: "exit 0"
volumes:
  db-volume:
