services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
      - /app/apps/api
    ports:
      - "3000:3000"
    tty: true
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
      - /app/apps/web
    restart: always
    ports:
      - "8080:3000"
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: db
    image: postgres:15.1-alpine3.17
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - db-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: "exit 0"
volumes:
  db-volume:
